### ISSUE TITLE
Allow archiving articles once they have been exported.

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/export#2]
Once an article has been exported, it will remain on the "Export" dashboard forever.

As an editor, I should be able to flag articles as archived once they have been exported.
It should still be possible to find these submissions either through the general article archive or with a custom page provided by the plugin.

Depends on https://github.com/BirkbeckCTP/janeway/issues/2737

**Comment by mauromsl** [comment]
There is an issue for adding this feature in Janeway core, so this plugin would only need a button to invoke the core behaviour

https://github.com/BirkbeckCTP/janeway/issues/2737

**Comment by ajrbyers** [comment]
@joemull can you add a Confirmable Button onto this one?
